### ISSUE TITLE
SF2WW Blanka headbutt bug sound

### ISSUE THREAD

**Issue by mikey1964** [jotego/jtcps1#100]
play as guile get to blanka stage block everything at some  point blanka will try to headbutt you and will do it 2 times in a row and each time the dying sound plays not sure if this happens in a real arcade board  .  also not sure if this is normal on a real arcade cps1 board as the plane moves the portraits flicker sometimes . the sf2ww arcade game seems to have alot of flicker when the speed increases hard to tell what is legit hardware bugs and what is a bug in the mister core not sure if other arcade revisions fix theses problems

**Comment by mikey1964** [comment]
here is a video https://gofile.io/d/RMOFbA

**Comment by jotego** [comment]
Hi,

I think your RBF may be a bad one. I made a bad update last week and had to delete it. The problem we fave is that the updater doesn't delete files, only updates. So I think you will have to manually delete the core.

I am preparing changes to the update approach to prevent these situations but it will still take a while until we have them ready. A first step will be announced today.

Thank you for reporting it.

**Comment by mikey1964** [comment]
ok i will delete the RBF by hand and then let the update download it again. i  will test again and let you know if it made a difference

**Comment by mikey1964** [comment]
i remove files manually   jtcps1_20210604.rbf - size 2.87 MB (3,013,356 bytes)
                                        jtcps15_20210604.rbf - size 2.91 MB (3,059,688 bytes)
is there anything else i need to remove. update install these files
jtcps1_20210604.rbf - 2.87 MB (3,013,356 bytes)
jtcps15_20210604.rbf - 2.91 MB (3,059,688 bytes)

 it made no difference
i got blanka to do the headbutt 3 times, in one set i got elephant sounds other 2 sets the sound had distortion and sound drop got like a robot like sound.

**Comment by mikey1964** [comment]
so iam guessing you fix this JT? i let blanka do his headbutt  i see nothing change still getting different sounds

**Comment by jotego** [comment]
Let me check again

**Comment by mikey1964** [comment]
which rbf are you using

**Comment by mikey1964** [comment]
iam using jtcps1_20211217

**Comment by jotego** [comment]
I think this is probably a bug in the original. I'll close it until new evidence pops up.

**Comment by mikey1964** [comment]
i have not been able to find a arcade machine to test this out but atleast i can confirm this happens in mame  also so its not my de10 or bad files . if i find a arcade machine i will let you know if it does the same thing
