### ISSUE TITLE
CPS 2 : Powered Gear Strategic Variant Armor Equipment (Japan 941024) - Graphical issues

### ISSUE THREAD

**Issue by wwark** [jotego/jtcps1#102]
You will see glitches on the screenshot below - produce with the 1st public release version.
![20210702_213102-screen](https://user-images.githubusercontent.com/469461/124321137-78dbd580-db7d-11eb-9b73-97abb5ed9725.png)
Thanks,

**Comment by wwark** [comment]
normally fixed by https://github.com/jotego/jtcps1/issues/119

**Comment by jotego** [comment]
Yes, it is fixed now :-)
