### ISSUE TITLE
CPS2- Dungeons & Dragons Tower of Doom - odd text highlight effect in service mode

### ISSUE THREAD

**Issue by Jimi369** [jotego/jtcps1#109]
When in service mode on D&D-Tower of Doom on the CPS2 core  the highlighted text seems to be slightly corrupted. At least it is different from other service modes on the cps2 core. 

I’ve looked on youtube for a video to compare but found no example. So it may be normal but I can’t tell.
Tested on two different Mister builds with the latest updates (as of november 13th)

![5A603B92-8770-4D3B-A07B-C7B8117C10BC](https://user-images.githubusercontent.com/87604246/141681843-66ce792b-eb7b-4004-8635-c99f4797181c.png)

**Comment by jotego** [comment]
It isn't consistent across games so I think it's correct but I'll leave the issue open in case new information arises.
