### ISSUE TITLE
CPS2 - eco fighter - missing foreground layer

### ISSUE THREAD

**Issue by Spacejockey-GH** [jotego/jtcps1#114]
En la pantalla 5 faltan todas las columnas verticales que deberian aparecer en primer plano no son dibujadas:

 Core del 20210828: 
![20210913_114814-screen](https://user-images.githubusercontent.com/72933535/133107468-4666aacb-083b-4119-b27d-9b6c8fa95af5.png)

Captura de MAME### 

![image](https://user-images.githubusercontent.com/72933535/133107901-a78ce61c-1072-43df-af85-49101f1bb02f.png)

Si mal no recuerdo esto se veía bien en versiones previas del core (Antes del fichero beta.zip)

**Comment by jotego** [comment]
Fixed in b23bbae
