### ISSUE TITLE
CPS2: Sprite gaps (Multiple games)

### ISSUE THREAD

**Issue by lsnderick** [jotego/jtcps1#117]
Recently I noticed there seems to visible "gaps" between some elements of the larger sprites. During the screen transitions those sprites seem to move out of sync with the rest of the image. So far I've seen this is in Vampire Savior 2 The Lord of Vampire (Intro), Vampire Hunter 2 Darkstalkers Revenge (Intro), Marvel Super Heroes (One of the stage background layers). Some screenshots:

![1](https://user-images.githubusercontent.com/55039803/147386048-d557b0c8-da1b-4b9f-898d-03961721a0c4.jpg)
![2](https://user-images.githubusercontent.com/55039803/147386049-d518a156-1058-42a8-a965-afbc1e82f0a0.jpg)
![3](https://user-images.githubusercontent.com/55039803/147386050-0120efa9-8193-4285-8eb3-42c4f2ceccf4.jpg)
![4](https://user-images.githubusercontent.com/55039803/147386051-f2707bf2-7131-460e-949c-a49d8fbafb76.jpg)
![5](https://user-images.githubusercontent.com/55039803/147386052-75b07c6e-44f0-4693-a503-939433ca2eb9.jpg)
![6](https://user-images.githubusercontent.com/55039803/147386053-beff2cdc-2bb9-4f74-bd28-b7e46181bc2c.jpg)

**Comment by jotego** [comment]
I think this is new. Maybe I broke something in an update. I don't remember seeing this problem before.

**Comment by jotego** [comment]
The problem was introduced in commit 0fdcb02

**Comment by jotego** [comment]
Fixed in c67b7e7
