### ISSUE TITLE
Rogue line on SSF2 player select screen

### ISSUE THREAD

**Issue by sqwirral** [jotego/jtcps1#121]
Issue appeared in **jtcps2_20211217**, previous version is okay.
Tested with Super Street Fighter II The New Challengers (World 931005).mra

![image](https://user-images.githubusercontent.com/243372/147275408-75442f25-0a3b-4128-a2b1-fd96a4d53ec3.png)

**Comment by jotego** [comment]
I this in fine in version b23bbae
That's 7th Jan. 2022
![20220107_164549-screen](https://user-images.githubusercontent.com/1863036/148577391-a3e35f17-c9c6-461c-9493-4b8b29a15aa0.png)
