### ISSUE TITLE
SF2: sprites drawn outside border on right hand side

### ISSUE THREAD

**Issue by fluxcorenz** [jotego/jtcps1#123]
![1644091080995](https://user-images.githubusercontent.com/4656357/152657027-9981b172-380c-40cb-ad7d-eb8e06b1ae74.jpg)

Foreground sprites are being drawn past the right hand side 'border', as described as the vertical line where the background is no longer drawn. This includes player characters, fireballs, crates etc.

A theory has been proposed that this is new behaviour since the shadowmask video processing has been added, but I have not confirmed this.

jtcps1_20220201

**Comment by jotego** [comment]
I think you're right, at some point in the development the two layer lengths got mismatched. This is from Ghouls'n Ghosts:

![imagen](https://user-images.githubusercontent.com/1863036/152657309-2dd3006f-6d51-4325-91ca-f87d5463e66e.png)

core version f83bc43 (you can see this code in the about screen)

**Comment by jotego** [comment]
Fixed
