### ISSUE TITLE
Ssf2

### ISSUE THREAD

**Issue by jotego** [jotego/jtcps1#124]
From Discord

in ssf2 in ken stage when you win a line flickers on the bottom of the boat as is moving up and down when you win on the score count. i  dont think this happens in real hardware can somebody check if it does happen there

**Comment by mikey1964** [comment]
might be normal

https://user-images.githubusercontent.com/56406421/153706640-32b3d04e-c95b-4007-8a05-cf230e2b0ec1.mp4

**Comment by jotego** [comment]
I think this is genuine then. I'll close the issue. Thanks for the video.
