### ISSUE TITLE
CPS1: DB15 no working on last MiSTer RC 20200515

### ISSUE THREAD

**Issue by yavimaya** [jotego/jtcps1#27]
DB15 SNAC is no working on last CPS1 core version, only D button from neogeo controller does something.
It was full working on v20200502.

**Comment by jotego** [comment]
Is DB15 SNAC the same as the NeoGeo gamepad on DB9 for Villena's boards?

**Comment by jotego** [comment]
Duplicated: https://github.com/jotego/jtbin/issues/93
