### ISSUE TITLE
CPS1 - bootlegs still in mra pack that dont work

### ISSUE THREAD

**Issue by eubrunosilva** [jotego/jtcps1#30]
Hi
at least for me, these mra that are in your pack dont work:
Street Fighter II': Champion Edition (RE, bootleg)
Street Fighter II  The World Warrior -Quicken Pt-I, bootleg-.mra
Street Fighter II  The World Warrior -Quicken, bootleg-.mra
Three Wonders -bootleg-.mra

**Comment by jotego** [comment]
Hi Bruno,

Maybe I should remove those bootlegs from jtbin but it's too much overhead to manage all MRA versions. I just accept PR for them.

Thanks
