### ISSUE TITLE
Street Fighter II: Champion Edition (USA) and Hyper Fighting (USA) MRAs

### ISSUE THREAD

**Issue by MJY71** [jotego/jtcps1#32]
The Street Fighter II: Champion Edition (USA) and Hyper Fighting (USA) Alternative MRAs all reference `rom index="0" zip="sf2.zip"`. They should instead reference `rom index="0" zip="sf2ce.zip"` and .`rom index="0" zip="sf2hf.zip"` respectively to work with merged ROM sets.

**Comment by jotego** [comment]
This was corrected but the issue was still open. Sorry. I'm closing it now. Thanks for reporting.
