### ISSUE TITLE
Strider: artefacts around Hiryu's character in certain positions.

### ISSUE THREAD

**Issue by Left-Empty** [jotego/jtcps1#39]
Hello, Hiryu seems to have black pixels around its sprite in certain positions, in a way reminding me a bit of [a past 3 Wonders issue]( https://github.com/jotego/jtbin/issues/39).

Here are two examples screenshots:

![Screen Shot](https://user-images.githubusercontent.com/62087454/83847882-4eff7780-a70d-11ea-8ac0-466d54329dff.png)
![Screen Shot 1](https://user-images.githubusercontent.com/62087454/83847888-50c93b00-a70d-11ea-87a5-0aa21b54d5cb.png)

Cheers!

**Comment by jotego** [comment]
I think those can be seen in MAME too. It may an artefact on the original board too.

**Comment by Left-Empty** [comment]
You are absolutely right: ironically, the "grosser Pixel" quality on my MAME setup made the thing less apparent than on the erotic direct video output of the MiSTer.
