### ISSUE TITLE
1941 - right edge of screen (in landscape HDMI display) has weird defect

### ISSUE THREAD

**Issue by c0d3h4x0r** [jotego/jtcps1#42]
Not sure if this is accurate of the original hardware or not, since I don't have original hardware to compare against.  But I've noticed that a few columns of pixels at the right edge of the screen don't appear to render correctly.

![20200607_053117250_iOS](https://user-images.githubusercontent.com/24398884/84125178-0a1b5f80-a9f1-11ea-8808-db0bbb70d6bf.jpg)

![20200607_052928367_iOS](https://user-images.githubusercontent.com/24398884/84125289-320ac300-a9f1-11ea-95af-7cb23189c05c.jpg)

**Comment by jotego** [comment]
I have tested it:
-It doesn't occur in MiST
-it occurs in MiSTer for analogue 15kHz output or HDMI (rotated or non rotated)
I'm going to investigate it

**Comment by jotego** [comment]
It only happens if the DIP switch for flip is enabled both in MiST and MiSTer. I didn't see it in MiST because the flip was off by default.
This points to some problem in the scroll data DMA involving the flip bit.

**Comment by jotego** [comment]
This is now fixed in commit 1b6327b7fc1201a27b7d390cb54178d6def1d08f
I'll create new RBF files. I'm closing the issue now.

**Comment by jotego** [comment]
This happens again in commit https://github.com/jotego/jtcps1/commit/bac12ec630ee3a4161137427fa8bc1f7a2836994 after fixing this assignment:
```
-wire        tile_vs  = vrender1== flip ? 9'd17 : 9'd12; // Vertical start, use for SCR3
+wire        tile_vs  = vrender1 == (flip ? 9'd17 : 9'd12); // Vertical start, use for SCR3
```

**Comment by M-Walrus** [comment]
Adding another example of this bug occurring in Varth:
https://youtu.be/A_6O4TvEd8E

Clouds and large boss ships exhibit this bug throughout the game.

**Comment by jotego** [comment]
This is fixed now locally. I will update the binaries later (today).
