### ISSUE TITLE
Button mapping in Readme

### ISSUE THREAD

**Issue by alessioscand** [jotego/jtcps1#43]
Hello,
It would be extremely helpful to include button mapping in the Readme, especially for titles such as Street Fighter. This would greatly simplify the configuration on SiDi. Thanks!

**Comment by jotego** [comment]
I have added it now. It is not that helpful because the button mapping is hidden from the core in MiST/SiDi. This is what I have added:

```
For MiST, the first 6 gamepad buttons are used for game buttons, the next 2 buttons are used for credit and start buttons. If there is still one button left in the gamepad, it will be used for pause.
```
