### ISSUE TITLE
Street Fighter Alpha Publicity USA - Bison corner graphic glitch

### ISSUE THREAD

**Issue by Aquas77** [jotego/jtcps1#44]
When Bison is hit in the left corner, occasionally his sprite disappears almost completely for a few frames. I've only observed this interaction in the left corner and with Bison, interacting with him against the corner usually.

This clip demonstrates the sprite disappearing, about 18 seconds into the clip, or at 87 seconds of Round 2 in game time when Charlie does a flash kick hitting Bison behind him, it happens quickly:

https://clips.twitch.tv/ReliableFrozenEagleBuddhaBar

I've asked a few other knowledgeable people of the game and they had never seen something like that before. I have also had one person try to recreate the glitch in MAME, without success.

**Comment by jotego** [comment]
This is fixed now in the CPS2 branch of the repository after simplifying the sprite engine. I will update the binary files next Friday (30th Jan).
