### ISSUE TITLE
Street Fighter II': Hyper Fighting (USA 921209)

### ISSUE THREAD

**Issue by mrfpga** [jotego/jtcps1#45]
In 1P mode on the Balrog (Claw) stage there are graphical glitches in the center of the stage, where the women are dancing in the background. Thre is a horizontal stripe below their feet with random colours that are permanently changing.

EDIT: The problem occured on the MiSTer core, not sure about the other systems.

**Comment by mrfpga** [comment]
@jotego 

Here is a video showcasing the bug, which is already present on Street Fighter II: Champion Edition:

image:
https://ibb.co/52Xc3Gs

video:
https://youtu.be/tHlIP2nwj3M?t=834

**Comment by cracklejoy** [comment]
This is not a bug.  Those are the lights for the stage and have been there for in sf2,sf2ce and sf2hf.
