### ISSUE TITLE
 Street Fighter Alpha: Warriors' Dreams (CPS Changer, Publicity USA 950727)

### ISSUE THREAD

**Issue by mrfpga** [jotego/jtcps1#46]
When playing 1P mode for some time random voice samples start playing like the knockout cry long before the round is over.

EDIT: The problem occured on the MiSTer core, not sure about the other systems.

**Comment by jotego** [comment]
I am going to assume this is related to #61. I will review the ADPCM chip controller. I am closing this here and will track it in #61.
