### ISSUE TITLE
SF2WW USA 911101 Flicker 

### ISSUE THREAD

**Issue by mikey1964** [jotego/jtcps1#48]
I check my ram and it seems ok pass all test . this flicker happens in all stages but easy to see in sagat stage . when you beat a fighter in this case sagat with a perfect hold the
 buttons to increase the speed of the score count it will cause some parts of the background to flicker in video look at the rock and sagat body on the ground video is in zip file. I do not have a arcade pcb to see if this is normal behavior

[IMG_3680[3444].zip](https://github.com/jotego/jtbin/files/4775746/IMG_3680.3444.zip)

**Comment by jotego** [comment]
Sorry it took me a while to get down to this issue. I agree with paulb-nl. Thank you both for reporting and resolving the issue.
