### ISSUE TITLE
CPS1 background layer missed in Three Wonders intro.

### ISSUE THREAD

**Issue by jegayon** [jotego/jtcps1#55]
There seems to be a problem in the background layer in the introduction of Three Wonders:

![IMG_20200628_203723](https://user-images.githubusercontent.com/67444654/85955709-d6dd4800-b980-11ea-8e56-2ab5a3a1705e.jpg)
![IMG_20200628_203810](https://user-images.githubusercontent.com/67444654/85955719-e52b6400-b980-11ea-8058-9735931843d2.jpg)
![IMG_20200628_203840](https://user-images.githubusercontent.com/67444654/85955722-ed839f00-b980-11ea-9fd4-f314a9e7ce04.jpg)
I hope these screenshots help.

**Comment by paulb-nl** [comment]
With Turbo enabled the backgrounds appear correctly.

**Comment by jotego** [comment]
Excellent hint. Thank you!

**Comment by jegayon** [comment]
Umm... I must have something wrong with my Mist core, because even with the Turbo option activated the issue remains....

**Comment by jotego** [comment]
Turbo function doesn't work in MiST from the OSD.
I can confirm that enabling turbo fixes it in MiSTer.

**Comment by jegayon** [comment]
Yes!!! I just recived my Mister today and I can confirm it too.

**Comment by jotego** [comment]
I tested it today using the new SDRAM controller, in case this was a memory contention issue. But the result was the same: no background for no turbo, background for turbo.

I wonder if the game should actually be set at 12MHz CPU permanently. I will try modifying the MRA to set 12MHz.

For my reference, this is how the scenes should look like.

![0009](https://user-images.githubusercontent.com/1863036/101354817-09775f00-3896-11eb-8c22-81602b307b47.png)
![0008](https://user-images.githubusercontent.com/1863036/101354824-0bd9b900-3896-11eb-8414-f46b3595c974.png)
![0010](https://user-images.githubusercontent.com/1863036/101354839-1005d680-3896-11eb-8a76-a79aa210c52c.png)

**Comment by jotego** [comment]
It happens even if CPU speed is set at 12MHz in the MRA file. Maybe the DMA starts a bit too early in the line.

**Comment by jotego** [comment]
Compiling with FORCE_GRAY does not show the backgrounds either, so it is not a missing palette problem.

**Comment by jotego** [comment]
Six months later...

The speed measurements I have made for issue #33 gave the final hint. When I applied the first fixed to the DMA (speeding the core by 5%), the backgrounds showed up. The problem was that the core was running too slow. I have it fixed locally and I will release the binary update today.

Thank you for reporting this and sorry for the long wait.
