### ISSUE TITLE
sf2,sf2ce bootlegs: many not working or simply missing

### ISSUE THREAD

**Issue by cracklejoy** [jotego/jtcps1#57]
These all exhibit graphical issues and keep rebooting:

Street Fighter II  The World Warrior -Quicken Pt-I, bootleg-.mra
![sf2qp1-1](https://user-images.githubusercontent.com/65365730/94728293-0314b600-032e-11eb-8d6c-c71c8c53a9fe.png)
![sf2qp1-2](https://user-images.githubusercontent.com/65365730/94728294-0314b600-032e-11eb-8587-c11367dcd31e.png)

Street Fighter II  The World Warrior -Quicken, bootleg-.mra
![sf2qp2-1](https://user-images.githubusercontent.com/65365730/94728334-10ca3b80-032e-11eb-8113-ed4af50fbe0a.png)
![sf2qp2-2](https://user-images.githubusercontent.com/65365730/94728335-10ca3b80-032e-11eb-88da-14fae72c7e24.png)

Examples such as these are simply missing and I'm not quite sure how to build my own mra with a new set:

sf2thndr          "Street Fighter II: The World Warrior (Thunder Edition, bootleg, set 1)"
sf2thndr2         "Street Fighter II: The World Warrior (Thunder Edition, bootleg, set 2)"

These simply bootup and play a barrel breaking:

Street Fighter II'  Champion Edition -Accelerator!, bootleg, set 1-.mra
Street Fighter II'  Champion Edition -Accelerator!, bootleg, set 2-.mra

I assume these all have some protection as this was common on these types of boards.  Not sure if this is implemented in the project as official releases seem to have no issues.

Lots of cleanup is required on the sf2* mra files as many of the sf2ce* reference uneeded files.

I have tried messing around with the mra files on the sf2q* releases but I think there is more to it than a simple incorrect mra.  I'm just piecing information together here as the documentation seems sparse.

**Comment by jotego** [comment]
Thank you for the detailed description. I am sorry the existence of those MRA mislead into thinking that those titles are supported.

The hardware for some of the bootlegs is quite different from the original hardware. It would be possible to add support, but I didn't want to mess with the design of the core too much for these games.
Now that I am adding multicore support to this repository for CPS1.5 and CPS2, it will be easier to add a bootleg variation of the core too.
Having said that, I don't plan to personally engage on it. I can accept other developers contributions for this.
