### ISSUE TITLE
Cadillacs & Dinosaurs - CPS1.5 (Beta 2)

### ISSUE THREAD

**Issue by ItsAtomico** [jotego/jtcps1#60]
Middle part of the car (door section) flickers when the Cadillac rolls into the screen. 

Can be tested at the start of Stage 2 or during attract mode. Tried USA, World and Asia roms, HDMI and CRT (via I/O board).

**Comment by jotego** [comment]
I think this is the same problem as #44

**Comment by jotego** [comment]
Just pasting the snapshot here for reference.

![20201211_073950-screen](https://user-images.githubusercontent.com/1863036/101877846-eea33400-3b8e-11eb-98dd-f992aa363705.png)

**Comment by jotego** [comment]
This is fixed now in the CPS2 branch of the repository after simplifying the sprite engine. I will update the binary files next Friday (30th Jan).
