### ISSUE TITLE
Ganbare! Marine Kun (Japan 2K0411) alway starts with RAM ERROR on MiST

### ISSUE THREAD

**Issue by gyurco** [jotego/jtcps1#63]
After reset, the ROM test looks OK, but after that, a big "RAM ERROR" in a blue backround pops up (and a Japanese message with red background).
The "Clear RAM" option doesn't affect it.

**Comment by jotego** [comment]
The game needs to have an extra RAM module that I didn't implement. It doesn't work well in MAME either and, as it is a ride, I think there is not so much interest from aficionados.

**Comment by gyurco** [comment]
Ah, if this is already known, then good. It's not a big loss.
