### ISSUE TITLE
CPS 1.5 halts and odd behaviour

### ISSUE THREAD

**Issue by rarcos** [jotego/jtcps1#66]
These crashes appear in release 201211.

There are random crashes in gameplay in both games:

![DSC_0097](https://user-images.githubusercontent.com/355739/101955715-115c3980-3bdd-11eb-8312-394d6ca44ffe.JPG)
![DSC_0098](https://user-images.githubusercontent.com/355739/101955744-1e792880-3bdd-11eb-88ff-9d32e1e1109c.JPG)
![DSC_0117](https://user-images.githubusercontent.com/355739/101955761-289b2700-3bdd-11eb-995b-567413c7dcb8.JPG)

Also, the games crash always at the same part in attract mode:

![DSC_0107](https://user-images.githubusercontent.com/355739/101955794-394b9d00-3bdd-11eb-8709-37a5acefe30c.JPG)
![DSC_0120](https://user-images.githubusercontent.com/355739/101955846-52544e00-3bdd-11eb-9aa4-18868cf05b8a.JPG)

Also, Cadillacs and Dinosaurs shows this behaviour: enter the first building, defeat all enemies, but don't get close to the window and the the time run out, when the player respawns the sprite will become unstable and then disappear, a few seconds later, the next scene will start. I'll try to capture footage from this if I can reproduce it again.

**Comment by jotego** [comment]
I think the issue is caused by excessive VDD ripple when all SDRAM banks are accessed in parallel. The new memory controller does that in order to improve data throughput. 

CPS1.5 with 4-bank interleaving had >700mVpp ripple
CPS1 with 1-bank access had <200mV ripple

![MiSTer 128MB The Punisher 96MHz](https://user-images.githubusercontent.com/1863036/102723867-91844c80-430b-11eb-821f-78d437176dff.png)
![MiSTer 128MB SF2 96MHz 1bank controller](https://user-images.githubusercontent.com/1863036/102723872-947f3d00-430b-11eb-8741-ebb98f3665f8.png)

**Comment by jotego** [comment]
Please try today's update and fill the poll here:
https://www.patreon.com/posts/45683205

**Comment by movisman** [comment]
Thanks so much for the tireless work on this particular issue.

I will update later on and fill the poll accordingly.

Your Patreon post mentions "I know that at least two SDRAM module builders are going to try to improve the modules." - are these separate improvements from what Alexey mentioned on a live chat he took part in the other night (https://youtu.be/sVTMWX0WUJk), or are the improvements linked? Here is the quote from Alexey:

![image](https://user-images.githubusercontent.com/18538104/103445586-1194a580-4c6e-11eb-90d2-264b3edee455.png)

Just curious if the proposed/future revision Alexey mentions has any relation to the improvements the builders are trying to implement into their modules.

Happy New Year and all the best for 2021.

Thanks!

**Comment by rarcos** [comment]
Thanks for your hard work. Latest ralease is stable for me.
