### ISSUE TITLE
WILLOW strange turbo behavior and unassigned buttons

### ISSUE THREAD

**Issue by Rageypoo** [jotego/jtcps1#67]
Hello, just wanted to let you know that in WILLOW if you use the attack or jump buttons it speeds up the game insanely fast in everything except once the game starts. It speeds up text, animation, and the countdown timer if you die. Is this normal?

Also, there is a button assignment that doesn't seem to exist. The game had 2 buttons, one for attack and one for jump, but when doing button assignments there is a third button that seems to be blank.

**Comment by jotego** [comment]
Hi, yes, it is normal. It is the way the game was designed. Check out the dip switches. There is a "turbo" function that might be related to that. I have not tried it out myself.

The third button is read at least in test mode. It seems not to be used during gameplay.

![20201230_173245-screen](https://user-images.githubusercontent.com/1863036/103370588-7795f700-4acd-11eb-999d-e8dbc8191b7a.png)
