### ISSUE TITLE
Sprite glitch in Strider

### ISSUE THREAD

**Issue by Hewhoisred** [jotego/jtcps1#72]
This may be related to the star field bug.  It's reproducible.  You'll see it all over the game when ascending/descending slopes.
![striderglitch](https://user-images.githubusercontent.com/47957258/104148970-5bc20900-5389-11eb-945f-b0e62eed7496.gif)

**Comment by Hewhoisred** [comment]
I've noticed the black garbage seems to happen right where the sword graphic comes out.

**Comment by Hewhoisred** [comment]
this may actually be correct behavior, the same glitch happens in MAME

**Comment by Hewhoisred** [comment]
correct arcade behavior, disregard

**Comment by jotego** [comment]
I did check this a long time and came to the same conclusion. It may be ok on some different game version. It is possible to hack the ROM to delete that pixel. This could actually be an error in the ROM dumping.
