### ISSUE TITLE
High-pitched rhythmic sound not present in original games

### ISSUE THREAD

**Issue by pacoarcade** [jotego/jtcps1#74]
In today's update (20210115) I've noticed much better sound in Street Fighter II. However, there is an annoying high-pitched sound that goes with the music.

This happens with the CPS1 games I've tested in MiSTer, taking the audio from the HDMI to VGA adapter and from the optical output via SPDIF.

[sf2ce-recording.zip](https://github.com/jotego/jtcps1/files/5824259/sf2ce-recording.zip)

**Comment by jotego** [comment]
Same as #75
