### ISSUE TITLE
CPS1 ADPCM drums? (sf2*, ffight*)

### ISSUE THREAD

**Issue by ItsAtomico** [jotego/jtcps1#75]
I might be in the wrong here, but I believe there's is some odd artifacting going on in the near the end of the kick drum sound on the ADPCM music for both Final Fight and the SF2 series. 

It's way too trebly, instead of being a dull "thump". Also seems like it has metallic/tinny sound after the proper drum.

Edit: In Final Fight the sound of enemy bodies hitting the floor also presents the same weird artifact/distortion as the drums. 

So yeah, I'm try to describe a sound in a foreign language, based on how  I _remember_ it from over a decade ago. Sorry about that and thanks for all your hard work.

**Comment by MJY71** [comment]
To me, it sounds like a tambourine is taped to the back of a bass drum whenever the kick drum hits. There is a ringing/jingling that should not be there.

**Comment by ItsAtomico** [comment]
Here's a few sound test codes for ffight: 

SFX:
0D is the knockdown sound. 6D appears to be the same one.
26 is the fast running steps from Sodom and maybe the Andores.

Stage music starts at address 40 and goes from there:
40 is Slums. 
41 is the basement with the fat dudes. Drums are even more prominent there

**Comment by ItsAtomico** [comment]
Fixed in jtcps1_20210117.

Thanks JT! Great work as always.

**Comment by SegaSnatcher** [comment]
> Fixed in jtcps1_20210117.
> 
> Thanks JT! Great work as always.

Where is the jtcps1_20210117 release at?

**Comment by jotego** [comment]
I uploaded it to the server last night. Just run the updater.
