### ISSUE TITLE
CPS1: Top row glitchy line of pixels in Street Fighter 2 Hyper Fighting.  

### ISSUE THREAD

**Issue by SegaSnatcher** [jotego/jtcps1#76]
I took a video of the issue.

https://www.youtube.com/watch?v=rmytFhembWg&feature=youtu.be

**Comment by jotego** [comment]
I attached a 96MHz compilation to the last Patreon post. I suppose there are no glitches there. This is the DMA being late for 48MHz SDRAM compilations.
