### ISSUE TITLE
CPS Cores do not support Custom AR:

### ISSUE THREAD

**Issue by Firebrandx** [jotego/jtcps1#83]
Wanted to experiment with my own integer scaling and noticed CPS games do not support this feature. For example:

[sf2ce]                               
vscale_mode=1
custom_aspect_ratio_1=48:35

Does not work at all (you can't select the custom AR mode in the OSD). It's vital in my opinion that all cores should allow the user complete control over AR and integer scaling. The "Original" and "Wide" modes are too limiting in scope.

**Comment by jotego** [comment]
I have added that now. Give me a couple of days to update the RBF files.
