### ISSUE TITLE
[MiSTer] CPS 1 : 1941 - Counter Attack (Japan) -  reverse display for rom check part on HDMI

### ISSUE THREAD

**Issue by wwark** [jotego/jtcps1#84]
This case is present just on HDMI, the case is ok on CRT.

I took screenshot with the Mister (option win+printscreen)
Rom Check
![20210204_074158-screen](https://user-images.githubusercontent.com/469461/107845878-389ed500-6ddf-11eb-8bc0-92430bf84cd6.png)
In game
![20210204_074211-screen](https://user-images.githubusercontent.com/469461/107845880-3dfc1f80-6ddf-11eb-9329-7b465f0de22d.png)

We saw trhe rom check is inverted compared during the game.

Thanks,

**Comment by jotego** [comment]
The screen orientation is controlled by the game. It seems like the game doesn't apply the flip setting until later. 
I'm afraid there isn't anything I can do.

**Comment by wwark** [comment]
Ok on Mame the behavior is not reverse on my LCD screen. Is Mame not have the correct behavior is this case ?
and also this issue is not present on CRT.

Thanks,

**Comment by jotego** [comment]
Set the flip setting in MAME and you will see it happening there too. 

For the CRT test, you must have run it with a different flip setting.

**Comment by wwark** [comment]
ok if i set flip Mame i saw the reverse display but it is inverted between the mister core and Mame.
Thanks no need to check more on this case.
