### ISSUE TITLE
Distorted voices, sfx in Super Puzzle Fighter

### ISSUE THREAD

**Issue by ItsAtomico** [jotego/jtcps1#86]
Voices tend to be distorted and shrill. Sound effects perhaps too trebly?

Distortion in announcer voice is easily noticeable. There's noise in the beginning and names are a bit garbled.

Sound test codes from 00C0 onward

**Comment by jotego** [comment]
Tech notes:
-Letting the M68k read the amplifier volume level does not fix it

**Comment by jotego** [comment]
Fixed
