### ISSUE TITLE
Street Fighter Alpha (CPS2) Ryu's ending

### ISSUE THREAD

**Issue by jotego** [jotego/jtcps1#87]
Ryu's ending screen looks black instead of showing an orange sky.

The sky is in layer SCR2, but SCR3 is configured to have priority over it, and it is all drawn with ink zero, which is not transparent. There must be some bit in the CPS-A/B chip to configure this, but we don't know it.

Reference: [CPS-B schematics](https://petitl.fr/cps2/DL-0921/#lut-assembly).

This is how it looks like:

![imagen](https://user-images.githubusercontent.com/1863036/109671681-961f7980-7b74-11eb-9868-4e98a57dab2b.png)

And this is how it should look:

![imagen](https://user-images.githubusercontent.com/1863036/109671635-89028a80-7b74-11eb-8c4d-29d515629ba5.png)

**Comment by jotego** [comment]
This seems to be a ROM mapping problem. CPS2 is assumed to cover all ROM space for the SCR banks, but in this case SCR3 may be pointing to an unmapped region, and thus should be read as FF's (and be transparent)

**Comment by Chocobobobo** [comment]
Just checked with my good friend Raph, who owns the blanka version of the PCB

![RYU](https://user-images.githubusercontent.com/23947970/109971802-e9b9d080-7cf6-11eb-863c-e516181ddba8.jpg)

**Comment by paulb-nl** [comment]
Street Fighter Zero PCB:
https://youtu.be/P-zc4VzSZgU?t=396

https://youtu.be/qRfPZ-rqujY?t=817

**Comment by Chocobobobo** [comment]
Yes, I watched every single video with it on YT. But with the poor image quality, it feels like some are using super eagle filter (meaning emulators are being used). This is why I am just trusting people I know, owning actual hardware (and streaming it for me to check).
But thanks Paul :)
