### ISSUE TITLE
CPS1 - Crackling audio on Street fighter 2 Zangief stages

### ISSUE THREAD

**Issue by jadflat** [jotego/jtcps1#88]
I'm getting some crackling on the music on Zangief stages on all three versions of Street Fighter 2. It does this over hdmi, 3.5mm and optical. Seems to be present only on the FM audio.

**Comment by jotego** [comment]
Thank you. I am tracking this issue [here](https://github.com/jotego/jtbin/issues/175).

**Comment by SatanicNemesis** [comment]
This has been closed but problem still persists

**Comment by jotego** [comment]
Because the issue is being tracked in the link above. I have just moved it.

**Comment by jotego** [comment]
I think that's just how the chip is supposed to sound. Other implementations sound the same: check track 20 [here](https://vgmrips.net/packs/pack/street-fighter-ii-the-world-warrior-cp-system).
