### ISSUE TITLE
CPS1: 1941 is upside down (?)

### ISSUE THREAD

**Issue by r4dius** [jotego/jtcps1#89]
Hi, I just tried running 1941 on mister with hdmi and the picture is upside down,
the "rotate screen" is enable, if disabled the image is rotate 45° as expected I guess.
Am I doing something wrong :'( ?

**Comment by jotego** [comment]
Go into the OSD menu, the DIP switches, then select flip and reboot.

**Comment by r4dius** [comment]
My bad, thanks :)
