### ISSUE TITLE
repo : dsp16 module missing

### ISSUE THREAD

**Issue by r4dius** [jotego/jtcps1#90]
Hi,
I've been trying compiling cps1.5 but the required jtdsp16 module repo doesn't exist anymore,
would it be possible to get an archive of this if it was deleted for a reason ?
Thanks

**Comment by jotego** [comment]
Please define the macro NOSOUND for compiling, you will get a working core but with no sound. 
The DSP16 isn't public yet.

**Comment by r4dius** [comment]
Oh ok no problem, thanks again :)
