### ISSUE TITLE
Graphical glitches on right side of screen (jtcps1_20210307)

### ISSUE THREAD

**Issue by MJY71** [jotego/jtcps1#91]
With release 20210307, there is a single pixel-wide column area that extends just beyond the right border of the screen where objects in certain layers scrolling to the right of the screen or objects that are already just off-screen show up as graphical garbage in certain places.

Screenshots of Street Fighter Alpha (CPS Changer) shown, but it happens in other games as well.

![20210307_181339](https://user-images.githubusercontent.com/18260997/110261582-627a9000-7f76-11eb-9c43-d73b1ddf4af8.jpg)

![20210307_181139](https://user-images.githubusercontent.com/18260997/110261584-66a6ad80-7f76-11eb-9866-4503476f81aa.jpg)

**Comment by PepAlacant** [comment]
There are other glitches that appear at Street Fighter II, II' and Turbo intro.
https://user-images.githubusercontent.com/75079781/110405822-7c54c980-8081-11eb-86a8-bf6005862283.MOV

**Comment by jotego** [comment]
Fixed in 210309
