### ISSUE TITLE
Check default background colour

### ISSUE THREAD

**Issue by jotego** [jotego/jtcps1#96]
When the CPS1 core was updated by the default background colour found in RE of CPS-B chip, it looked weird. Same goes for CPS1.5 compilations (CPS1.5 hasn't been updated publicly with this feature).
Double check it.

**Comment by advert665** [comment]
Would this explain why 1941 has a green background on the title screen for me, instead of black, or should I raise another issue for that?

**Comment by jotego** [comment]
It is the same issue, thanks.
